version: "3.1"

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: investor
      POSTGRES_PASSWORD: m0n3y
      POSTGRES_DB: adalpha
    ports:
      - 5000:5432
    volumes:
      - ./postgres_db_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - ad-alpha
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    networks:
      - ad-alpha
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
    depends_on:
      - elastic
    ports:
      - 5601:5601
    networks:
      - ad-alpha
#  api:
#    image: golang:1.6.1-alpine
#    volumes:
#      - .:/go/src/go-with-compose
#    working_dir: /go/src/AdAlpha/api
#    command: go run main.go
#    depends_on:
#      - postgres-db
#      - elastic
#    links:
#      - postgres-db
#      - elastic
#    ports:
#      - 5431:5431

networks:
  ad-alpha:


